ERROR - 2022-09-01 05:34:09 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\bentokopi\bentokopi\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 D:\bentokopi\bentokopi\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', '', '', '', 3306, '', 0)
#1 D:\bentokopi\bentokopi\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\bentokopi\bentokopi\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\bentokopi\bentokopi\vendor\codeigniter4\framework\system\Database\BaseConnection.php(1385): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#4 D:\bentokopi\bentokopi\vendor\codeigniter4\framework\system\Database\BaseConnection.php(1419): CodeIgniter\Database\BaseConnection->listTables()
#5 D:\bentokopi\bentokopi\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(759): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#6 D:\bentokopi\bentokopi\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(167): CodeIgniter\Database\MigrationRunner->ensureTable()
#7 D:\bentokopi\bentokopi\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 D:\bentokopi\bentokopi\vendor\codeigniter4\framework\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 D:\bentokopi\bentokopi\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(65): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 D:\bentokopi\bentokopi\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(51): CodeIgniter\CLI\CommandRunner->index(Array)
#11 D:\bentokopi\bentokopi\vendor\codeigniter4\framework\system\CodeIgniter.php(897): CodeIgniter\CLI\CommandRunner->_remap('index', Array)
#12 D:\bentokopi\bentokopi\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 D:\bentokopi\bentokopi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 D:\bentokopi\bentokopi\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 D:\bentokopi\bentokopi\spark(98): CodeIgniter\CLI\Console->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\bentokopi\bentokopi\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 D:\bentokopi\bentokopi\vendor\codeigniter4\framework\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\bentokopi\bentokopi\vendor\codeigniter4\framework\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\bentokopi\bentokopi\vendor\codeigniter4\framework\system\Database\BaseConnection.php(1385): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#3 D:\bentokopi\bentokopi\vendor\codeigniter4\framework\system\Database\BaseConnection.php(1419): CodeIgniter\Database\BaseConnection->listTables()
#4 D:\bentokopi\bentokopi\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(759): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#5 D:\bentokopi\bentokopi\vendor\codeigniter4\framework\system\Database\MigrationRunner.php(167): CodeIgniter\Database\MigrationRunner->ensureTable()
#6 D:\bentokopi\bentokopi\vendor\codeigniter4\framework\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#7 D:\bentokopi\bentokopi\vendor\codeigniter4\framework\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#8 D:\bentokopi\bentokopi\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(65): CodeIgniter\CLI\Commands->run('migrate', Array)
#9 D:\bentokopi\bentokopi\vendor\codeigniter4\framework\system\CLI\CommandRunner.php(51): CodeIgniter\CLI\CommandRunner->index(Array)
#10 D:\bentokopi\bentokopi\vendor\codeigniter4\framework\system\CodeIgniter.php(897): CodeIgniter\CLI\CommandRunner->_remap('index', Array)
#11 D:\bentokopi\bentokopi\vendor\codeigniter4\framework\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#12 D:\bentokopi\bentokopi\vendor\codeigniter4\framework\system\CodeIgniter.php(336): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 D:\bentokopi\bentokopi\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#14 D:\bentokopi\bentokopi\spark(98): CodeIgniter\CLI\Console->run()
#15 {main}
CRITICAL - 2022-09-01 10:33:34 --> fopen(/storage/ssd5/691/19482691/public_html/vendor/myth/auth/src/Authentication/Passwords/_dictionary.txt): Failed to open stream: No such file or directory
in FCPATH/vendor/myth/auth/src/Authentication/Passwords/DictionaryValidator.php on line 26.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
 2 FCPATH/vendor/myth/auth/src/Authentication/Passwords/DictionaryValidator.php(26): fopen()
 3 FCPATH/vendor/myth/auth/src/Authentication/Passwords/PasswordValidator.php(46): Myth\Auth\Authentication\Passwords\DictionaryValidator->check()
 4 FCPATH/vendor/myth/auth/src/Authentication/Passwords/ValidationRules.php(42): Myth\Auth\Authentication\Passwords\PasswordValidator->check()
 5 SYSTEMPATH/Validation/Validation.php(314): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password()
 6 SYSTEMPATH/Validation/Validation.php(175): CodeIgniter\Validation\Validation->processRules()
 7 SYSTEMPATH/Controller.php(140): CodeIgniter\Validation\Validation->run()
 8 FCPATH/vendor/myth/auth/src/Controllers/AuthController.php(164): CodeIgniter\Controller->validate()
 9 SYSTEMPATH/CodeIgniter.php(904): Myth\Auth\Controllers\AuthController->attemptRegister()
10 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
11 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
12 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 10:42:46 --> fopen(/storage/ssd5/691/19482691/public_html/vendor/myth/auth/src/Authentication/Passwords/_dictionary.txt): Failed to open stream: No such file or directory
in FCPATH/vendor/myth/auth/src/Authentication/Passwords/DictionaryValidator.php on line 26.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
 2 FCPATH/vendor/myth/auth/src/Authentication/Passwords/DictionaryValidator.php(26): fopen()
 3 FCPATH/vendor/myth/auth/src/Authentication/Passwords/PasswordValidator.php(46): Myth\Auth\Authentication\Passwords\DictionaryValidator->check()
 4 FCPATH/vendor/myth/auth/src/Authentication/Passwords/ValidationRules.php(42): Myth\Auth\Authentication\Passwords\PasswordValidator->check()
 5 SYSTEMPATH/Validation/Validation.php(314): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password()
 6 SYSTEMPATH/Validation/Validation.php(175): CodeIgniter\Validation\Validation->processRules()
 7 SYSTEMPATH/Controller.php(140): CodeIgniter\Validation\Validation->run()
 8 FCPATH/vendor/myth/auth/src/Controllers/AuthController.php(164): CodeIgniter\Controller->validate()
 9 SYSTEMPATH/CodeIgniter.php(904): Myth\Auth\Controllers\AuthController->attemptRegister()
10 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
11 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
12 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 10:46:35 --> fopen(/storage/ssd5/691/19482691/public_html/vendor/myth/auth/src/Authentication/Passwords/_dictionary.txt): Failed to open stream: No such file or directory
in FCPATH/vendor/myth/auth/src/Authentication/Passwords/DictionaryValidator.php on line 26.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
 2 FCPATH/vendor/myth/auth/src/Authentication/Passwords/DictionaryValidator.php(26): fopen()
 3 FCPATH/vendor/myth/auth/src/Authentication/Passwords/PasswordValidator.php(46): Myth\Auth\Authentication\Passwords\DictionaryValidator->check()
 4 FCPATH/vendor/myth/auth/src/Authentication/Passwords/ValidationRules.php(42): Myth\Auth\Authentication\Passwords\PasswordValidator->check()
 5 SYSTEMPATH/Validation/Validation.php(314): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password()
 6 SYSTEMPATH/Validation/Validation.php(175): CodeIgniter\Validation\Validation->processRules()
 7 SYSTEMPATH/Controller.php(140): CodeIgniter\Validation\Validation->run()
 8 FCPATH/vendor/myth/auth/src/Controllers/AuthController.php(164): CodeIgniter\Controller->validate()
 9 SYSTEMPATH/CodeIgniter.php(904): Myth\Auth\Controllers\AuthController->attemptRegister()
10 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
11 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
12 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 11:02:49 --> fopen(/storage/ssd5/691/19482691/public_html/vendor/myth/auth/src/Authentication/Passwords/_dictionary.txt): Failed to open stream: No such file or directory
in FCPATH/vendor/myth/auth/src/Authentication/Passwords/DictionaryValidator.php on line 26.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
 2 FCPATH/vendor/myth/auth/src/Authentication/Passwords/DictionaryValidator.php(26): fopen()
 3 FCPATH/vendor/myth/auth/src/Authentication/Passwords/PasswordValidator.php(46): Myth\Auth\Authentication\Passwords\DictionaryValidator->check()
 4 FCPATH/vendor/myth/auth/src/Authentication/Passwords/ValidationRules.php(42): Myth\Auth\Authentication\Passwords\PasswordValidator->check()
 5 SYSTEMPATH/Validation/Validation.php(314): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password()
 6 SYSTEMPATH/Validation/Validation.php(175): CodeIgniter\Validation\Validation->processRules()
 7 SYSTEMPATH/Controller.php(140): CodeIgniter\Validation\Validation->run()
 8 FCPATH/vendor/myth/auth/src/Controllers/AuthController.php(164): CodeIgniter\Controller->validate()
 9 SYSTEMPATH/CodeIgniter.php(904): Myth\Auth\Controllers\AuthController->attemptRegister()
10 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
11 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
12 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 11:04:32 --> The route for "Auth.register" cannot be found.
in SYSTEMPATH/Helpers/url_helper.php on line 542.
 1 SYSTEMPATH/Helpers/url_helper.php(542): CodeIgniter\Router\Exceptions\RouterException::forInvalidRoute()
 2 APPPATH/Views/auth/Register.php(40): url_to()
 3 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/auth/Register.php')
 4 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH/Common.php(1142): CodeIgniter\View\View->render()
 6 FCPATH/vendor/myth/auth/src/Controllers/AuthController.php(412): view()
 7 FCPATH/vendor/myth/auth/src/Controllers/AuthController.php(133): Myth\Auth\Controllers\AuthController->_render()
 8 SYSTEMPATH/CodeIgniter.php(904): Myth\Auth\Controllers\AuthController->register()
 9 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
10 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
11 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 11:04:35 --> The route for "Auth.register" cannot be found.
in SYSTEMPATH/Helpers/url_helper.php on line 542.
 1 SYSTEMPATH/Helpers/url_helper.php(542): CodeIgniter\Router\Exceptions\RouterException::forInvalidRoute()
 2 APPPATH/Views/auth/Register.php(40): url_to()
 3 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/auth/Register.php')
 4 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH/Common.php(1142): CodeIgniter\View\View->render()
 6 APPPATH/Controllers/Auth.php(10): view()
 7 SYSTEMPATH/CodeIgniter.php(904): App\Controllers\Auth->Register()
 8 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
 9 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
10 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 11:04:37 --> The route for "Auth.register" cannot be found.
in SYSTEMPATH/Helpers/url_helper.php on line 542.
 1 SYSTEMPATH/Helpers/url_helper.php(542): CodeIgniter\Router\Exceptions\RouterException::forInvalidRoute()
 2 APPPATH/Views/auth/Register.php(40): url_to()
 3 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/auth/Register.php')
 4 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH/Common.php(1142): CodeIgniter\View\View->render()
 6 APPPATH/Controllers/Auth.php(10): view()
 7 SYSTEMPATH/CodeIgniter.php(904): App\Controllers\Auth->Register()
 8 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
 9 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
10 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 11:04:41 --> The route for "Auth.register" cannot be found.
in SYSTEMPATH/Helpers/url_helper.php on line 542.
 1 SYSTEMPATH/Helpers/url_helper.php(542): CodeIgniter\Router\Exceptions\RouterException::forInvalidRoute()
 2 APPPATH/Views/auth/Register.php(40): url_to()
 3 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/auth/Register.php')
 4 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH/Common.php(1142): CodeIgniter\View\View->render()
 6 APPPATH/Controllers/Auth.php(10): view()
 7 SYSTEMPATH/CodeIgniter.php(904): App\Controllers\Auth->Register()
 8 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
 9 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
10 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 11:29:06 --> The route for "lregister" cannot be found.
in SYSTEMPATH/Helpers/url_helper.php on line 542.
 1 SYSTEMPATH/Helpers/url_helper.php(542): CodeIgniter\Router\Exceptions\RouterException::forInvalidRoute()
 2 APPPATH/Views/auth/Register.php(40): url_to()
 3 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/auth/Register.php')
 4 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH/Common.php(1142): CodeIgniter\View\View->render()
 6 APPPATH/Controllers/Auth.php(10): view()
 7 SYSTEMPATH/CodeIgniter.php(904): App\Controllers\Auth->Register()
 8 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
 9 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
10 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 11:29:32 --> fopen(/storage/ssd5/691/19482691/public_html/vendor/myth/auth/src/Authentication/Passwords/_dictionary.txt): Failed to open stream: No such file or directory
in FCPATH/vendor/myth/auth/src/Authentication/Passwords/DictionaryValidator.php on line 26.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
 2 FCPATH/vendor/myth/auth/src/Authentication/Passwords/DictionaryValidator.php(26): fopen()
 3 FCPATH/vendor/myth/auth/src/Authentication/Passwords/PasswordValidator.php(46): Myth\Auth\Authentication\Passwords\DictionaryValidator->check()
 4 FCPATH/vendor/myth/auth/src/Authentication/Passwords/ValidationRules.php(42): Myth\Auth\Authentication\Passwords\PasswordValidator->check()
 5 SYSTEMPATH/Validation/Validation.php(314): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password()
 6 SYSTEMPATH/Validation/Validation.php(175): CodeIgniter\Validation\Validation->processRules()
 7 SYSTEMPATH/Controller.php(140): CodeIgniter\Validation\Validation->run()
 8 FCPATH/vendor/myth/auth/src/Controllers/AuthController.php(164): CodeIgniter\Controller->validate()
 9 SYSTEMPATH/CodeIgniter.php(904): Myth\Auth\Controllers\AuthController->attemptRegister()
10 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
11 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
12 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 11:33:35 --> fopen(/storage/ssd5/691/19482691/public_html/vendor/myth/auth/src/Authentication/Passwords/_dictionary.txt): Failed to open stream: No such file or directory
in FCPATH/vendor/myth/auth/src/Authentication/Passwords/DictionaryValidator.php on line 26.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
 2 FCPATH/vendor/myth/auth/src/Authentication/Passwords/DictionaryValidator.php(26): fopen()
 3 FCPATH/vendor/myth/auth/src/Authentication/Passwords/PasswordValidator.php(46): Myth\Auth\Authentication\Passwords\DictionaryValidator->check()
 4 FCPATH/vendor/myth/auth/src/Authentication/Passwords/ValidationRules.php(42): Myth\Auth\Authentication\Passwords\PasswordValidator->check()
 5 SYSTEMPATH/Validation/Validation.php(314): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password()
 6 SYSTEMPATH/Validation/Validation.php(175): CodeIgniter\Validation\Validation->processRules()
 7 SYSTEMPATH/Controller.php(140): CodeIgniter\Validation\Validation->run()
 8 FCPATH/vendor/myth/auth/src/Controllers/AuthController.php(164): CodeIgniter\Controller->validate()
 9 SYSTEMPATH/CodeIgniter.php(904): Myth\Auth\Controllers\AuthController->attemptRegister()
10 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
11 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
12 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 11:35:56 --> fopen(/storage/ssd5/691/19482691/public_html/vendor/myth/auth/src/Authentication/Passwords/_dictionary.txt): Failed to open stream: No such file or directory
in FCPATH/vendor/myth/auth/src/Authentication/Passwords/DictionaryValidator.php on line 26.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
 2 FCPATH/vendor/myth/auth/src/Authentication/Passwords/DictionaryValidator.php(26): fopen()
 3 FCPATH/vendor/myth/auth/src/Authentication/Passwords/PasswordValidator.php(46): Myth\Auth\Authentication\Passwords\DictionaryValidator->check()
 4 FCPATH/vendor/myth/auth/src/Authentication/Passwords/ValidationRules.php(42): Myth\Auth\Authentication\Passwords\PasswordValidator->check()
 5 SYSTEMPATH/Validation/Validation.php(314): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password()
 6 SYSTEMPATH/Validation/Validation.php(175): CodeIgniter\Validation\Validation->processRules()
 7 SYSTEMPATH/Controller.php(140): CodeIgniter\Validation\Validation->run()
 8 FCPATH/vendor/myth/auth/src/Controllers/AuthController.php(164): CodeIgniter\Controller->validate()
 9 SYSTEMPATH/CodeIgniter.php(904): Myth\Auth\Controllers\AuthController->attemptRegister()
10 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
11 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
12 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 11:43:11 --> The route for "emailActivation" cannot be found.
in SYSTEMPATH/Helpers/url_helper.php on line 542.
 1 SYSTEMPATH/Helpers/url_helper.php(542): CodeIgniter\Router\Exceptions\RouterException::forInvalidRoute()
 2 APPPATH/Views/auth/Register.php(40): url_to()
 3 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/auth/Register.php')
 4 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH/Common.php(1142): CodeIgniter\View\View->render()
 6 APPPATH/Controllers/Auth.php(10): view()
 7 SYSTEMPATH/CodeIgniter.php(904): App\Controllers\Auth->Register()
 8 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
 9 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
10 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 11:43:13 --> The route for "emailActivation" cannot be found.
in SYSTEMPATH/Helpers/url_helper.php on line 542.
 1 SYSTEMPATH/Helpers/url_helper.php(542): CodeIgniter\Router\Exceptions\RouterException::forInvalidRoute()
 2 APPPATH/Views/auth/Register.php(40): url_to()
 3 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/auth/Register.php')
 4 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH/Common.php(1142): CodeIgniter\View\View->render()
 6 APPPATH/Controllers/Auth.php(10): view()
 7 SYSTEMPATH/CodeIgniter.php(904): App\Controllers\Auth->Register()
 8 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
 9 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
10 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 11:43:15 --> The route for "emailActivation" cannot be found.
in SYSTEMPATH/Helpers/url_helper.php on line 542.
 1 SYSTEMPATH/Helpers/url_helper.php(542): CodeIgniter\Router\Exceptions\RouterException::forInvalidRoute()
 2 APPPATH/Views/auth/Register.php(40): url_to()
 3 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/auth/Register.php')
 4 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH/Common.php(1142): CodeIgniter\View\View->render()
 6 APPPATH/Controllers/Auth.php(10): view()
 7 SYSTEMPATH/CodeIgniter.php(904): App\Controllers\Auth->Register()
 8 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
 9 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
10 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 11:43:17 --> The route for "emailActivation" cannot be found.
in SYSTEMPATH/Helpers/url_helper.php on line 542.
 1 SYSTEMPATH/Helpers/url_helper.php(542): CodeIgniter\Router\Exceptions\RouterException::forInvalidRoute()
 2 APPPATH/Views/auth/Register.php(40): url_to()
 3 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/auth/Register.php')
 4 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH/Common.php(1142): CodeIgniter\View\View->render()
 6 APPPATH/Controllers/Auth.php(10): view()
 7 SYSTEMPATH/CodeIgniter.php(904): App\Controllers\Auth->Register()
 8 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
 9 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
10 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 11:43:18 --> The route for "emailActivation" cannot be found.
in SYSTEMPATH/Helpers/url_helper.php on line 542.
 1 SYSTEMPATH/Helpers/url_helper.php(542): CodeIgniter\Router\Exceptions\RouterException::forInvalidRoute()
 2 APPPATH/Views/auth/Register.php(40): url_to()
 3 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/auth/Register.php')
 4 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH/Common.php(1142): CodeIgniter\View\View->render()
 6 APPPATH/Controllers/Auth.php(10): view()
 7 SYSTEMPATH/CodeIgniter.php(904): App\Controllers\Auth->Register()
 8 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
 9 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
10 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 11:43:20 --> The route for "emailActivation" cannot be found.
in SYSTEMPATH/Helpers/url_helper.php on line 542.
 1 SYSTEMPATH/Helpers/url_helper.php(542): CodeIgniter\Router\Exceptions\RouterException::forInvalidRoute()
 2 APPPATH/Views/auth/Register.php(40): url_to()
 3 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/auth/Register.php')
 4 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH/Common.php(1142): CodeIgniter\View\View->render()
 6 APPPATH/Controllers/Auth.php(10): view()
 7 SYSTEMPATH/CodeIgniter.php(904): App\Controllers\Auth->Register()
 8 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
 9 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
10 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 11:43:26 --> The route for "emailActivation" cannot be found.
in SYSTEMPATH/Helpers/url_helper.php on line 542.
 1 SYSTEMPATH/Helpers/url_helper.php(542): CodeIgniter\Router\Exceptions\RouterException::forInvalidRoute()
 2 APPPATH/Views/auth/Register.php(40): url_to()
 3 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/auth/Register.php')
 4 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH/Common.php(1142): CodeIgniter\View\View->render()
 6 APPPATH/Controllers/Auth.php(10): view()
 7 SYSTEMPATH/CodeIgniter.php(904): App\Controllers\Auth->Register()
 8 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
 9 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
10 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 11:54:40 --> fopen(/storage/ssd5/691/19482691/public_html/app/ThirdParty/myth-auth/src/Authentication/Passwords/_dictionary.txt): Failed to open stream: No such file or directory
in APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/DictionaryValidator.php on line 26.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
 2 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/DictionaryValidator.php(26): fopen()
 3 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/PasswordValidator.php(46): Myth\Auth\Authentication\Passwords\DictionaryValidator->check()
 4 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/ValidationRules.php(42): Myth\Auth\Authentication\Passwords\PasswordValidator->check()
 5 SYSTEMPATH/Validation/Validation.php(314): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password()
 6 SYSTEMPATH/Validation/Validation.php(175): CodeIgniter\Validation\Validation->processRules()
 7 SYSTEMPATH/Controller.php(140): CodeIgniter\Validation\Validation->run()
 8 APPPATH/ThirdParty/myth-auth/src/Controllers/AuthController.php(164): CodeIgniter\Controller->validate()
 9 SYSTEMPATH/CodeIgniter.php(904): Myth\Auth\Controllers\AuthController->attemptRegister()
10 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
11 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
12 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 12:04:34 --> fopen(/storage/ssd5/691/19482691/public_html/app/ThirdParty/myth-auth/src/Authentication/Passwords/_dictionary.txt): Failed to open stream: No such file or directory
in APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/DictionaryValidator.php on line 26.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
 2 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/DictionaryValidator.php(26): fopen()
 3 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/PasswordValidator.php(46): Myth\Auth\Authentication\Passwords\DictionaryValidator->check()
 4 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/ValidationRules.php(42): Myth\Auth\Authentication\Passwords\PasswordValidator->check()
 5 SYSTEMPATH/Validation/Validation.php(314): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password()
 6 SYSTEMPATH/Validation/Validation.php(175): CodeIgniter\Validation\Validation->processRules()
 7 SYSTEMPATH/Controller.php(140): CodeIgniter\Validation\Validation->run()
 8 APPPATH/ThirdParty/myth-auth/src/Controllers/AuthController.php(164): CodeIgniter\Controller->validate()
 9 SYSTEMPATH/CodeIgniter.php(904): Myth\Auth\Controllers\AuthController->attemptRegister()
10 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
11 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
12 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 12:30:33 --> fopen(/storage/ssd5/691/19482691/public_html/app/ThirdParty/myth-auth/src/Authentication/Passwords/_dictionary.txt): Failed to open stream: No such file or directory
in APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/DictionaryValidator.php on line 26.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
 2 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/DictionaryValidator.php(26): fopen()
 3 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/PasswordValidator.php(46): Myth\Auth\Authentication\Passwords\DictionaryValidator->check()
 4 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/ValidationRules.php(42): Myth\Auth\Authentication\Passwords\PasswordValidator->check()
 5 SYSTEMPATH/Validation/Validation.php(314): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password()
 6 SYSTEMPATH/Validation/Validation.php(175): CodeIgniter\Validation\Validation->processRules()
 7 SYSTEMPATH/Controller.php(140): CodeIgniter\Validation\Validation->run()
 8 APPPATH/ThirdParty/myth-auth/src/Controllers/AuthController.php(164): CodeIgniter\Controller->validate()
 9 SYSTEMPATH/CodeIgniter.php(904): Myth\Auth\Controllers\AuthController->attemptRegister()
10 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
11 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
12 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 12:33:16 --> fopen(/storage/ssd5/691/19482691/public_html/app/ThirdParty/myth-auth/src/Authentication/Passwords/_dictionary.txt): Failed to open stream: No such file or directory
in APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/DictionaryValidator.php on line 26.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
 2 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/DictionaryValidator.php(26): fopen()
 3 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/PasswordValidator.php(46): Myth\Auth\Authentication\Passwords\DictionaryValidator->check()
 4 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/ValidationRules.php(42): Myth\Auth\Authentication\Passwords\PasswordValidator->check()
 5 SYSTEMPATH/Validation/Validation.php(314): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password()
 6 SYSTEMPATH/Validation/Validation.php(175): CodeIgniter\Validation\Validation->processRules()
 7 SYSTEMPATH/Controller.php(140): CodeIgniter\Validation\Validation->run()
 8 APPPATH/ThirdParty/myth-auth/src/Controllers/AuthController.php(164): CodeIgniter\Controller->validate()
 9 SYSTEMPATH/CodeIgniter.php(904): Myth\Auth\Controllers\AuthController->attemptRegister()
10 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
11 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
12 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 12:38:58 --> fopen(/storage/ssd5/691/19482691/public_html/app/ThirdParty/myth-auth/src/Authentication/Passwords/_dictionary.txt): Failed to open stream: No such file or directory
in APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/DictionaryValidator.php on line 26.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
 2 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/DictionaryValidator.php(26): fopen()
 3 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/PasswordValidator.php(46): Myth\Auth\Authentication\Passwords\DictionaryValidator->check()
 4 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/ValidationRules.php(42): Myth\Auth\Authentication\Passwords\PasswordValidator->check()
 5 SYSTEMPATH/Validation/Validation.php(314): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password()
 6 SYSTEMPATH/Validation/Validation.php(175): CodeIgniter\Validation\Validation->processRules()
 7 SYSTEMPATH/Controller.php(140): CodeIgniter\Validation\Validation->run()
 8 APPPATH/ThirdParty/myth-auth/src/Controllers/AuthController.php(164): CodeIgniter\Controller->validate()
 9 SYSTEMPATH/CodeIgniter.php(904): Myth\Auth\Controllers\AuthController->attemptRegister()
10 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
11 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
12 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 12:40:46 --> fopen(/storage/ssd5/691/19482691/public_html/app/ThirdParty/myth-auth/src/Authentication/Passwords/_dictionary.txt): Failed to open stream: No such file or directory
in APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/DictionaryValidator.php on line 26.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
 2 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/DictionaryValidator.php(26): fopen()
 3 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/PasswordValidator.php(46): Myth\Auth\Authentication\Passwords\DictionaryValidator->check()
 4 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/ValidationRules.php(42): Myth\Auth\Authentication\Passwords\PasswordValidator->check()
 5 SYSTEMPATH/Validation/Validation.php(314): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password()
 6 SYSTEMPATH/Validation/Validation.php(175): CodeIgniter\Validation\Validation->processRules()
 7 SYSTEMPATH/Controller.php(140): CodeIgniter\Validation\Validation->run()
 8 APPPATH/ThirdParty/myth-auth/src/Controllers/AuthController.php(164): CodeIgniter\Controller->validate()
 9 SYSTEMPATH/CodeIgniter.php(904): Myth\Auth\Controllers\AuthController->attemptRegister()
10 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
11 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
12 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 12:44:32 --> fopen(/storage/ssd5/691/19482691/public_html/app/ThirdParty/myth-auth/src/Authentication/Passwords/_dictionary.txt): Failed to open stream: No such file or directory
in APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/DictionaryValidator.php on line 26.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
 2 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/DictionaryValidator.php(26): fopen()
 3 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/PasswordValidator.php(46): Myth\Auth\Authentication\Passwords\DictionaryValidator->check()
 4 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/ValidationRules.php(42): Myth\Auth\Authentication\Passwords\PasswordValidator->check()
 5 SYSTEMPATH/Validation/Validation.php(314): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password()
 6 SYSTEMPATH/Validation/Validation.php(175): CodeIgniter\Validation\Validation->processRules()
 7 SYSTEMPATH/Controller.php(140): CodeIgniter\Validation\Validation->run()
 8 APPPATH/ThirdParty/myth-auth/src/Controllers/AuthController.php(164): CodeIgniter\Controller->validate()
 9 SYSTEMPATH/CodeIgniter.php(904): Myth\Auth\Controllers\AuthController->attemptRegister()
10 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
11 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
12 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 12:48:07 --> fopen(/storage/ssd5/691/19482691/public_html/app/ThirdParty/myth-auth/src/Authentication/Passwords/_dictionary.txt): Failed to open stream: No such file or directory
in APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/DictionaryValidator.php on line 26.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
 2 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/DictionaryValidator.php(26): fopen()
 3 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/PasswordValidator.php(46): Myth\Auth\Authentication\Passwords\DictionaryValidator->check()
 4 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/ValidationRules.php(42): Myth\Auth\Authentication\Passwords\PasswordValidator->check()
 5 SYSTEMPATH/Validation/Validation.php(314): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password()
 6 SYSTEMPATH/Validation/Validation.php(175): CodeIgniter\Validation\Validation->processRules()
 7 SYSTEMPATH/Controller.php(140): CodeIgniter\Validation\Validation->run()
 8 APPPATH/ThirdParty/myth-auth/src/Controllers/AuthController.php(164): CodeIgniter\Controller->validate()
 9 SYSTEMPATH/CodeIgniter.php(904): Myth\Auth\Controllers\AuthController->attemptRegister()
10 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
11 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
12 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 12:55:05 --> fopen(/storage/ssd5/691/19482691/public_html/app/ThirdParty/myth-auth/src/Authentication/Passwords/_dictionary.txt): Failed to open stream: No such file or directory
in APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/DictionaryValidator.php on line 26.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
 2 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/DictionaryValidator.php(26): fopen()
 3 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/PasswordValidator.php(46): Myth\Auth\Authentication\Passwords\DictionaryValidator->check()
 4 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/ValidationRules.php(42): Myth\Auth\Authentication\Passwords\PasswordValidator->check()
 5 SYSTEMPATH/Validation/Validation.php(314): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password()
 6 SYSTEMPATH/Validation/Validation.php(175): CodeIgniter\Validation\Validation->processRules()
 7 SYSTEMPATH/Controller.php(140): CodeIgniter\Validation\Validation->run()
 8 APPPATH/ThirdParty/myth-auth/src/Controllers/AuthController.php(164): CodeIgniter\Controller->validate()
 9 SYSTEMPATH/CodeIgniter.php(904): Myth\Auth\Controllers\AuthController->attemptRegister()
10 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
11 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
12 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 13:05:05 --> fopen(/storage/ssd5/691/19482691/public_html/app/ThirdParty/myth-auth/src/Authentication/Passwords/_dictionary.txt): Failed to open stream: No such file or directory
in APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/DictionaryValidator.php on line 26.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
 2 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/DictionaryValidator.php(26): fopen()
 3 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/PasswordValidator.php(46): Myth\Auth\Authentication\Passwords\DictionaryValidator->check()
 4 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/ValidationRules.php(42): Myth\Auth\Authentication\Passwords\PasswordValidator->check()
 5 SYSTEMPATH/Validation/Validation.php(314): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password()
 6 SYSTEMPATH/Validation/Validation.php(175): CodeIgniter\Validation\Validation->processRules()
 7 SYSTEMPATH/Controller.php(140): CodeIgniter\Validation\Validation->run()
 8 APPPATH/ThirdParty/myth-auth/src/Controllers/AuthController.php(164): CodeIgniter\Controller->validate()
 9 SYSTEMPATH/CodeIgniter.php(904): Myth\Auth\Controllers\AuthController->attemptRegister()
10 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
11 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
12 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 13:07:41 --> fopen(/storage/ssd5/691/19482691/public_html/app/ThirdParty/myth-auth/src/Authentication/Passwords/_dictionary.txt): Failed to open stream: No such file or directory
in APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/DictionaryValidator.php on line 26.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
 2 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/DictionaryValidator.php(26): fopen()
 3 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/PasswordValidator.php(46): Myth\Auth\Authentication\Passwords\DictionaryValidator->check()
 4 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/ValidationRules.php(42): Myth\Auth\Authentication\Passwords\PasswordValidator->check()
 5 SYSTEMPATH/Validation/Validation.php(314): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password()
 6 SYSTEMPATH/Validation/Validation.php(175): CodeIgniter\Validation\Validation->processRules()
 7 SYSTEMPATH/Controller.php(140): CodeIgniter\Validation\Validation->run()
 8 APPPATH/ThirdParty/myth-auth/src/Controllers/AuthController.php(164): CodeIgniter\Controller->validate()
 9 SYSTEMPATH/CodeIgniter.php(904): Myth\Auth\Controllers\AuthController->attemptRegister()
10 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
11 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
12 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 13:09:54 --> fopen(/storage/ssd5/691/19482691/public_html/app/ThirdParty/myth-auth/src/Authentication/Passwords/_dictionary.txt): Failed to open stream: No such file or directory
in APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/DictionaryValidator.php on line 26.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
 2 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/DictionaryValidator.php(26): fopen()
 3 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/PasswordValidator.php(46): Myth\Auth\Authentication\Passwords\DictionaryValidator->check()
 4 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/ValidationRules.php(42): Myth\Auth\Authentication\Passwords\PasswordValidator->check()
 5 SYSTEMPATH/Validation/Validation.php(314): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password()
 6 SYSTEMPATH/Validation/Validation.php(175): CodeIgniter\Validation\Validation->processRules()
 7 SYSTEMPATH/Controller.php(140): CodeIgniter\Validation\Validation->run()
 8 APPPATH/ThirdParty/myth-auth/src/Controllers/AuthController.php(164): CodeIgniter\Controller->validate()
 9 SYSTEMPATH/CodeIgniter.php(904): Myth\Auth\Controllers\AuthController->attemptRegister()
10 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
11 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
12 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 22:37:42 --> fopen(/storage/ssd5/691/19482691/public_html/app/ThirdParty/myth-auth/src/Authentication/Passwords/_dictionary.txt): Failed to open stream: No such file or directory
in APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/DictionaryValidator.php on line 26.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
 2 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/DictionaryValidator.php(26): fopen()
 3 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/PasswordValidator.php(46): Myth\Auth\Authentication\Passwords\DictionaryValidator->check()
 4 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/ValidationRules.php(42): Myth\Auth\Authentication\Passwords\PasswordValidator->check()
 5 SYSTEMPATH/Validation/Validation.php(314): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password()
 6 SYSTEMPATH/Validation/Validation.php(175): CodeIgniter\Validation\Validation->processRules()
 7 SYSTEMPATH/Controller.php(140): CodeIgniter\Validation\Validation->run()
 8 APPPATH/ThirdParty/myth-auth/src/Controllers/AuthController.php(164): CodeIgniter\Controller->validate()
 9 SYSTEMPATH/CodeIgniter.php(904): Myth\Auth\Controllers\AuthController->attemptRegister()
10 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
11 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
12 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 22:38:51 --> fopen(/storage/ssd5/691/19482691/public_html/app/ThirdParty/myth-auth/src/Authentication/Passwords/_dictionary.txt): Failed to open stream: No such file or directory
in APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/DictionaryValidator.php on line 26.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
 2 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/DictionaryValidator.php(26): fopen()
 3 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/PasswordValidator.php(46): Myth\Auth\Authentication\Passwords\DictionaryValidator->check()
 4 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/ValidationRules.php(42): Myth\Auth\Authentication\Passwords\PasswordValidator->check()
 5 SYSTEMPATH/Validation/Validation.php(314): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password()
 6 SYSTEMPATH/Validation/Validation.php(175): CodeIgniter\Validation\Validation->processRules()
 7 SYSTEMPATH/Controller.php(140): CodeIgniter\Validation\Validation->run()
 8 APPPATH/ThirdParty/myth-auth/src/Controllers/AuthController.php(164): CodeIgniter\Controller->validate()
 9 SYSTEMPATH/CodeIgniter.php(904): Myth\Auth\Controllers\AuthController->attemptRegister()
10 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
11 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
12 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 22:40:56 --> The route for "Auth.register" cannot be found.
in SYSTEMPATH/Helpers/url_helper.php on line 542.
 1 SYSTEMPATH/Helpers/url_helper.php(542): CodeIgniter\Router\Exceptions\RouterException::forInvalidRoute()
 2 APPPATH/Views/auth/Register.php(42): url_to()
 3 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/auth/Register.php')
 4 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH/Common.php(1142): CodeIgniter\View\View->render()
 6 APPPATH/Controllers/Auth.php(10): view()
 7 SYSTEMPATH/CodeIgniter.php(904): App\Controllers\Auth->Register()
 8 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
 9 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
10 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 22:41:00 --> The route for "Auth.register" cannot be found.
in SYSTEMPATH/Helpers/url_helper.php on line 542.
 1 SYSTEMPATH/Helpers/url_helper.php(542): CodeIgniter\Router\Exceptions\RouterException::forInvalidRoute()
 2 APPPATH/Views/auth/Register.php(42): url_to()
 3 SYSTEMPATH/View/View.php(213): include('APPPATH/Views/auth/Register.php')
 4 SYSTEMPATH/View/View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH/Common.php(1142): CodeIgniter\View\View->render()
 6 APPPATH/Controllers/Auth.php(10): view()
 7 SYSTEMPATH/CodeIgniter.php(904): App\Controllers\Auth->Register()
 8 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
 9 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
10 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 22:45:26 --> fopen(/storage/ssd5/691/19482691/public_html/app/ThirdParty/myth-auth/src/Authentication/Passwords/_dictionary.txt): Failed to open stream: No such file or directory
in APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/DictionaryValidator.php on line 26.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
 2 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/DictionaryValidator.php(26): fopen()
 3 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/PasswordValidator.php(46): Myth\Auth\Authentication\Passwords\DictionaryValidator->check()
 4 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/ValidationRules.php(42): Myth\Auth\Authentication\Passwords\PasswordValidator->check()
 5 SYSTEMPATH/Validation/Validation.php(314): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password()
 6 SYSTEMPATH/Validation/Validation.php(175): CodeIgniter\Validation\Validation->processRules()
 7 SYSTEMPATH/Controller.php(140): CodeIgniter\Validation\Validation->run()
 8 APPPATH/ThirdParty/myth-auth/src/Controllers/AuthController.php(164): CodeIgniter\Controller->validate()
 9 SYSTEMPATH/CodeIgniter.php(904): Myth\Auth\Controllers\AuthController->attemptRegister()
10 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
11 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
12 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 22:55:01 --> fopen(/storage/ssd5/691/19482691/public_html/app/ThirdParty/myth-auth/src/Authentication/Passwords/_dictionary.txt): Failed to open stream: No such file or directory
in APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/DictionaryValidator.php on line 26.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler()
 2 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/DictionaryValidator.php(26): fopen()
 3 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/PasswordValidator.php(46): Myth\Auth\Authentication\Passwords\DictionaryValidator->check()
 4 APPPATH/ThirdParty/myth-auth/src/Authentication/Passwords/ValidationRules.php(42): Myth\Auth\Authentication\Passwords\PasswordValidator->check()
 5 SYSTEMPATH/Validation/Validation.php(314): Myth\Auth\Authentication\Passwords\ValidationRules->strong_password()
 6 SYSTEMPATH/Validation/Validation.php(175): CodeIgniter\Validation\Validation->processRules()
 7 SYSTEMPATH/Controller.php(140): CodeIgniter\Validation\Validation->run()
 8 APPPATH/ThirdParty/myth-auth/src/Controllers/AuthController.php(164): CodeIgniter\Controller->validate()
 9 SYSTEMPATH/CodeIgniter.php(904): Myth\Auth\Controllers\AuthController->attemptRegister()
10 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController()
11 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest()
12 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2022-09-01 22:59:53 --> Cannot declare class App\Controllers\Auth, because the name is already in use
in APPPATH/Controllers/Auth.php on line 6.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2022-09-01 22:59:58 --> Cannot declare class App\Controllers\Auth, because the name is already in use
in APPPATH/Controllers/Auth.php on line 6.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
